version: "3.9"

services:
  app:
    build: .
    container_name: apiserver
    ports:
      - "8080:8080"
    
    volumes:
      - .:/app
    networks:
      - app_network


volumes:
  db_data:

networks:
  app_network:
    driver: bridge
