version: "3.9"

services:
  app:
    build: .
    container_name: apiserver
    ports:
      - "8080:8080"
    environment:
      - ENV_FILE=/app/.env
    volumes:
      - .:/app
    networks:
      - app_network

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
